version: '3.8'

services:
  device_client_runtime:
    container_name: device_client_runtime
    build:
      context: ./..
      dockerfile: ./examples/minimal_offload_sync.dockerfile
    network_mode: host
    volumes:
    - .:/cognit/examples
    - /etc/response_daemon:/cognit/queue
