---
 # The options below are applicable to all jammer types
 # Select Frequency operating range (1=2.4GHz, 2=5GHz) | default = 1
 band: 1
 # Select Jammer Type (1=constant, 2=sweeping, 3=random channel hopping) | default = 1
 jammer: 2
 # Select Type of Jamming (1=proactive, 2=reactive) | default = 1
 jamming: 2
 # Select Jamming waveform (1=single tone, 2=QPSK modulated, 3=gaussian noise) | default = 3
 waveform: 2
 # Enter Jammer transmit power in dBm (Min = -40dBm, Max = 13dBm) | default = 6dBm
 power: 6
 # Enter channel jamming duration in sec | default = 10s
 t_jamming: 5
 
 # The options below are optional depending on the jammer of choice
 # Enter total runtime duration in sec | default = 200s
 duration: 100 # This option doesn't apply to constant jammer
 # Enter distance between adjacent channels in MHz (Min = 1MHz, Max = 20MHz) | default = 20MHz
 ch_dist: 20 # This option doesn't apply to constant jammer and 5GHz band
 # Enter the frequency to Jam in MHz | default = 2462MHz
 freq: 2462 # This option only applies to constant jammer
 #Select channel allocation (1=UNII-1, 2=UNII-2a, 3=UNII-2c, 4=UNII-3)
 allocation: 1 # This option only applies to 5GHz band

 #Additional features
 # Enable memory feature (1=yes|0=no) | default = 0
 memory: 0 # This options only applies to reactive jammer
 # Enable energy savings feature (1=yes|0=no) | default = 0
 savings: 0
 # If Energy savings is enabled, then Enter duty cycle in % | default = 100
 duty_cycle: 100
 # Select type of spectrum sensing (1=energy detection, 2=Machine Learning-based detection) | default = 1
 detector: 1
 
